### PR TITLE
Fix typo in allow_sideload example

### PR DESCRIPTION
**Pull request by Subtletree**

### CODE REVIEW

**Comment by richmolj** [comment]
@Subtletree whoops, thanks for the edit! I think you want to edit `concepts.md` and then run `bundle exec jekyll build` or `bundle exec jekyll serve` to build the compiled files though.

**Comment by Subtletree** [comment]
struggling 😅

**Comment by richmolj** [comment]
Somehow I don't see a change to `concepts.md` in the diff?

**Comment by Subtletree** [comment]
Think `concepts.md` just iterates over each concept. So the change is in `_includes/docs/sideloading/example.html`.

**Comment by richmolj** [comment]
Ah, of course. Thanks again!

**Pull request merged**
